---
title: "Los Angeles Education"
execute: 
  echo: false
---

```{r}
#| message: false

library(tidycensus)
library(tidyverse)
library(leaflet)
library(scales)  # for percent formatting
library(RColorBrewer)
```



```{r}
#| message: false
# Variable for percentage of bachelor's degree or higher (ACS 5-year)
# B15003_022 to B15003_025 represent bachelor's or higher education levels
# B15003_001 is total population age 25+

x <- get_acs(
  geography = "tract",
  variables = c(total = "B15003_001", 
                bachelor = "B15003_022", 
                masters = "B15003_023",
                professional = "B15003_024", 
                doctorate = "B15003_025"),
  county = "Los Angeles",
  state = "CA",
  year = 2022,
  geometry = TRUE,
  output = "wide"
) |> 
  mutate(pct_bachelors_or_higher = 100 * (
    bachelorE + mastersE + professionalE + doctorateE) / totalE)



```


```{r}
#| warning: false
pal <- colorBin(
  palette = "YlGnBu",
  domain = x$pct_bachelors_or_higher,
  bins = c(0, 10, 25, 40, 55, 70, 85, 100),
  na.color = "transparent"
)

# Labels for hover
labels <- sprintf(
  "<strong>%s</strong><br/>%.1f%% with Bachelor's or higher",
  x$NAME,
  x$pct_bachelors_or_higher
) %>% lapply(htmltools::HTML)

# Build interactive leaflet map
leaflet(data = x) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(
    fillColor = ~pal(pct_bachelors_or_higher),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlightOptions = highlightOptions(
      weight = 2,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.9,
      bringToFront = TRUE
    ),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "13px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = pal,
    values = ~pct_bachelors_or_higher,
    opacity = 0.7,
    title = "% Bachelor's+",
    position = "bottomright"
  )
```